# Generated by Django 4.2.7 on 2023-11-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id_produk",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nama_produk", models.CharField(max_length=164)),
                ("harga", models.IntegerField(default=0, max_length=164)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id_status", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama_status", models.CharField(max_length=164)),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id_kategori", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=164)),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
    ]
