# Generated by Django 4.2.7 on 2023-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="harga",
            field=models.IntegerField(default=0),
        ),
    ]
