# Generated by Django 4.2.7 on 2023-11-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_product_harga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="produk",
            field=models.ForeignKey(
                db_column="id_produk",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="produk",
            field=models.ForeignKey(
                db_column="id_produk",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.product",
            ),
        ),
    ]
