# Generated by Django 4.2.7 on 2023-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_category_produk_alter_status_produk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id_produk",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
