# Generated by Django 4.2.7 on 2023-11-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_id_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='produk',
            field=models.ForeignKey(db_column='id_produk', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='status',
            name='produk',
            field=models.ForeignKey(db_column='id_produk', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
