# Generated by Django 4.2.7 on 2023-11-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_produk_alter_status_produk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='produk',
        ),
        migrations.RemoveField(
            model_name='status',
            name='produk',
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.ForeignKey(db_column='id_kategori', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(db_column='id_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
    ]
