# Generated by Django 4.2.7 on 2023-11-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id_produk",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
